#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# Disable terminal "bracketed paste" mode (DECSET 2004) for the life of this
# script. Terminals that enable it (mintty/Git Bash included) wrap every
# pasted chunk in invisible ESC[200~ ... ESC[201~ markers so a readline-aware
# prompt can tell paste from typing. This script's `read`/`read -s` calls are
# plain and don't strip those markers, so they (and, apparently, stray
# terminal redraw bytes) were landing as literal characters inside pasted
# secrets — confirmed corrupting several values captured before this fix.
printf '\e[?2004l'
trap 'printf "\e[?2004h"' EXIT

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: ticket 01 — foundation account creation + deploy pipeline.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$SCRIPT_DIR/setup-wizard.env"

XCCONFIG_EXAMPLE="$REPO_ROOT/ios/Secrets.xcconfig.example"
XCCONFIG="$REPO_ROOT/ios/Secrets.xcconfig"

# _xcconfig_set KEY VALUE upserts "KEY = value" into ios/Secrets.xcconfig,
# applying the "//" -> "/$()/" comment-escaping trick (see
# Secrets.xcconfig.example) whenever the value contains "://".
_xcconfig_set() {
  local key="$1" value="$2" tmp escaped
  [[ -f "$XCCONFIG" ]] || cp "$XCCONFIG_EXAMPLE" "$XCCONFIG"
  escaped="$value"
  [[ "$escaped" == *"://"* ]] && escaped="${escaped/:\/\//:\/\$()\/}"
  tmp=$(mktemp)
  grep -vE "^${key}[[:space:]]*=" "$XCCONFIG" > "$tmp" || true
  printf '%s = %s\n' "$key" "$escaped" >> "$tmp"
  mv "$tmp" "$XCCONFIG"
  printf '  %s✓ wrote%s %s → ios/Secrets.xcconfig\n' "$GREEN" "$RESET" "$key"
}

TOTAL_STAGES=11

banner "Wake Mate: foundation setup (ticket 01)"

# ── Stage 1: GitHub repo + push ────────────────────────────────────────────
stage "GitHub repository"
say "Everything else (CI, secrets, environments) needs the code pushed to a"
say "GitHub repo first."
if ! command -v gh >/dev/null 2>&1; then
  warn "gh (GitHub CLI) isn't installed. Later stages can set secrets/"
  warn "environments for you automatically if it's installed and logged in —"
  warn "otherwise this wizard falls back to manual instructions."
  step "Install it from https://cli.github.com, then run: gh auth login"
  open_url "https://cli.github.com"
  pause "Press Enter once gh is installed (or to skip and do things manually):"
fi
if command -v gh >/dev/null 2>&1 && ! gh auth status >/dev/null 2>&1; then
  step "Authenticate gh:"
  say "  gh auth login"
  pause "Press Enter once you've run 'gh auth login' (or to skip):"
fi
if git -C "$REPO_ROOT" remote get-url origin >/dev/null 2>&1; then
  note "origin remote already set: $(git -C "$REPO_ROOT" remote get-url origin)"
else
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    ask GITHUB_REPO_NAME "Repo name to create (e.g. yourname/wake-mate):"
    if confirm "Create private GitHub repo '$GITHUB_REPO_NAME' and push?"; then
      gh repo create "$GITHUB_REPO_NAME" --private --source "$REPO_ROOT" --remote origin || \
        warn "gh repo create failed — create it manually and add the remote."
    fi
  else
    step "Create a new (private is fine) repo at:"
    open_url "https://github.com/new"
    ask GITHUB_REPO_URL "Paste the new repo's URL (e.g. https://github.com/you/wake-mate):"
    git -C "$REPO_ROOT" remote add origin "${GITHUB_REPO_URL}.git" 2>/dev/null || \
      warn "couldn't add remote automatically — run: git remote add origin ${GITHUB_REPO_URL}.git"
  fi
fi
if confirm "Commit and push the current branch to origin now?"; then
  git -C "$REPO_ROOT" push -u origin HEAD || warn "push failed — push manually once ready."
fi

# ── Stage 2: Supabase project ──────────────────────────────────────────────
stage "Supabase project (eu-west-1)"
say "This is the Postgres + Auth + Edge Functions backend. Region MUST be"
say "eu-west-1 (Ireland) — already locked in per the project's GDPR decision."
open_url "https://supabase.com/dashboard"
step "Sign in / sign up, then 'New project'."
step "Region: EU West (Ireland) — eu-west-1. Plan: Free is fine to start."
step "Once created, set a strong database password when prompted — you'll"
step "need it again in a moment."
pause "Press Enter once the project has finished provisioning:"
step "Project Settings -> General: copy the 'Reference ID'."
ask SUPABASE_PROJECT_ID "Paste the Project Reference ID:"
step "Project Settings -> API: copy the 'Project URL' and the 'anon public' key."
ask SUPABASE_URL "Paste the Project URL (https://<ref>.supabase.co):"
ask SUPABASE_ANON_KEY "Paste the anon public key:"
step "Project Settings -> Database: the password you set at creation (reset"
step "it there if you didn't note it down)."
ask_secret SUPABASE_DB_PASSWORD "Paste the database password:"
write_env SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
set_secret SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
set_secret SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"

# ── Stage 3: Supabase CLI access token ─────────────────────────────────────
stage "Supabase CLI access token"
say "CI authenticates to Supabase (to run 'supabase db push' / 'functions"
say "deploy') with a personal access token, separate from the DB password."
open_url "https://supabase.com/dashboard/account/tokens"
step "Generate a new token (name it something like 'wake-mate-ci')."
ask_secret SUPABASE_ACCESS_TOKEN "Paste the access token:"
write_env SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
set_secret SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"

# ── Stage 4: GitHub production environment ─────────────────────────────────
stage "GitHub 'production' environment (manual approval gate)"
say "Ticket 01 requires one manual approval before backend deploys touch the"
say "live project. This can only be configured in the GitHub web UI — gh"
say "can't do this part."
if [[ -n "${GITHUB_REPO_NAME:-}" ]]; then
  open_url "https://github.com/${GITHUB_REPO_NAME}/settings/environments"
elif git -C "$REPO_ROOT" remote get-url origin >/dev/null 2>&1; then
  note "your repo: $(git -C "$REPO_ROOT" remote get-url origin)"
  step "Go to that repo -> Settings -> Environments."
else
  step "Go to your repo -> Settings -> Environments."
fi
step "New environment, name it exactly: production"
step "Under 'Deployment protection rules', enable 'Required reviewers' and"
step "add yourself."
pause "Press Enter once the 'production' environment exists with a required reviewer:"

# ── Stage 5: APNs GitHub Actions secrets (deferrable) ──────────────────────
stage "GitHub Actions secrets: APNs (deferrable)"
say "SUPABASE_ACCESS_TOKEN / SUPABASE_PROJECT_ID / SUPABASE_DB_PASSWORD are"
say "already set from stages 2-3. These three are for ticket 18 (push"
say "notifications) — nothing in ticket 01 creates an APNs key, so unless"
say "you already have one from elsewhere, skip this entirely; the deploy"
say "pipeline tolerates them being blank."
if confirm "Set the APNs secrets now? (say no to skip all three)"; then
  ask_secret APNS_AUTH_KEY_BASE64 "Base64-encoded APNs .p8 key (blank to skip):"
  [[ -n "$APNS_AUTH_KEY_BASE64" ]] && set_secret APNS_AUTH_KEY_BASE64 "$APNS_AUTH_KEY_BASE64"
  ask APNS_KEY_ID "APNs Key ID (blank to skip):"
  [[ -n "$APNS_KEY_ID" ]] && set_secret APNS_KEY_ID "$APNS_KEY_ID"
  ask APNS_TEAM_ID "Apple Developer Team ID (blank to skip):"
  [[ -n "$APNS_TEAM_ID" ]] && set_secret APNS_TEAM_ID "$APNS_TEAM_ID"
else
  note "skipped — set these later with: gh secret set <NAME>"
  SKIPPED+=("APNS_AUTH_KEY_BASE64, APNS_KEY_ID, APNS_TEAM_ID (ticket 18)")
fi

# ── Stage 6: Apple Developer account + App ID ──────────────────────────────
stage "Apple Developer account + App ID"
say "This is web-only — no Mac needed for this part."
open_url "https://developer.apple.com/programs/enroll/"
step "Enroll in the Apple Developer Program (\$99/year) if you haven't."
pause "Press Enter once enrollment is complete (can take up to 48h to approve):"
open_url "https://developer.apple.com/account/resources/identifiers/list/bundleId"
step "Register a new App ID / bundle identifier, e.g. com.<yourname>.wakemate."
ask WAKEMATE_BUNDLE_ID "Bundle identifier you registered:"
write_env WAKEMATE_BUNDLE_ID "$WAKEMATE_BUNDLE_ID"
warn "This repo currently uses 'com.wakemate' as a placeholder. Update"
warn "ios/project.yml manually: 'bundleIdPrefix' and the app target's"
warn "PRODUCT_BUNDLE_IDENTIFIER to match what you just registered, then"
warn "commit that change."
SKIPPED+=("update ios/project.yml bundleIdPrefix / PRODUCT_BUNDLE_IDENTIFIER to $WAKEMATE_BUNDLE_ID")

# ── Stage 7: Sentry ─────────────────────────────────────────────────────────
stage "Sentry (crash reporting)"
open_url "https://sentry.io/signup/"
step "Sign up (or sign in), then create a new project with platform 'Apple'"
step "(iOS/Swift) named something like 'wake-mate-ios'."
step "On the project's Getting Started page, copy its DSN."
ask_secret SENTRY_DSN "Paste the iOS project's DSN:"
_xcconfig_set SENTRY_DSN "$SENTRY_DSN"
write_env SENTRY_DSN "$SENTRY_DSN"
note "That's the client-side DSN for the iOS app."
if confirm "Also create a second Sentry project for the backend Edge Functions now?"; then
  step "Create another project, platform 'Deno' (or generic Node), named"
  step "e.g. 'wake-mate-edge'. Copy its DSN."
  ask_secret SENTRY_DSN_EDGE "Paste the Edge Functions project's DSN:"
  set_secret SENTRY_DSN_EDGE "$SENTRY_DSN_EDGE"
else
  note "skipped — you can add SENTRY_DSN_EDGE as a GitHub secret later."
fi

# ── Stage 8: TelemetryDeck ──────────────────────────────────────────────────
stage "TelemetryDeck (analytics)"
open_url "https://telemetrydeck.com/dashboard/registration/organization"
step "Sign up, create an organization if prompted, then create a new app"
step "named 'Wake Mate'."
step "Copy the app's App ID (looks like a UUID) from its settings page."
ask TELEMETRYDECK_APP_ID "Paste the TelemetryDeck App ID:"
_xcconfig_set TELEMETRYDECK_APP_ID "$TELEMETRYDECK_APP_ID"
write_env TELEMETRYDECK_APP_ID "$TELEMETRYDECK_APP_ID"

# ── Stage 9: fill ios/Secrets.xcconfig ─────────────────────────────────────
stage "ios/Secrets.xcconfig"
say "Writing the values captured so far into ios/Secrets.xcconfig (gitignored)."
_xcconfig_set SUPABASE_URL "$SUPABASE_URL"
_xcconfig_set SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
note "SENTRY_DSN and TELEMETRYDECK_APP_ID were already written in stages 7-8."
say "ios/Secrets.xcconfig is now complete and gitignored — it will never be"
say "committed. ios/Secrets.xcconfig.example (the template, no real values)"
say "is what stays in git."

# ── Stage 10: push + verify CI ─────────────────────────────────────────────
stage "Push and verify CI"
note "ios/Secrets.xcconfig is gitignored; only Secrets.xcconfig.example (the template) is ever committed."
if confirm "Commit and push now?"; then
  git -C "$REPO_ROOT" add -A
  git -C "$REPO_ROOT" commit -m "chore: run setup wizard for ticket 01 infrastructure" || \
    note "nothing to commit (maybe already committed)."
  git -C "$REPO_ROOT" push || warn "push failed — push manually."
fi
if [[ -n "${GITHUB_REPO_NAME:-}" ]]; then
  open_url "https://github.com/${GITHUB_REPO_NAME}/actions"
elif git -C "$REPO_ROOT" remote get-url origin >/dev/null 2>&1; then
  note "check Actions at: $(git -C "$REPO_ROOT" remote get-url origin)/actions"
fi
step "Confirm: 'Deploy backend' is either green or waiting on the"
step "'production' environment's manual approval (click 'Review deployments'"
step "-> Approve to let it run)."
step "Confirm: 'iOS build' runs on a macOS runner and goes green."
pause "Press Enter once you've checked both workflows:"

# ── Stage 11: Mac access reminder ──────────────────────────────────────────
stage "One-time Mac access (to actually run the app)"
say "Everything up to here works with zero Mac/iPad access: the code"
say "compiles and deploys entirely via GitHub's cloud runners."
say "To actually tap through the app yourself, you'll need ~30-60 minutes"
say "on a Mac once (a rented cloud Mac like MacinCloud, a friend's, a"
say "library/university one) to:"
step "Install Xcode + XcodeGen (brew install xcodegen)."
step "cd ios && xcodegen generate"
step "Open WakeMate.xcodeproj, run on an iOS 26+ simulator."
note "Nothing else in this setup requires repeating that — CI covers"
note "'does it build' on every push after that."
SKIPPED+=("one-time ~30-60min Mac session to run 'xcodegen generate' + Xcode")

finish
